-- ============================================================
-- V1__init.sql
-- Farmville Initial Schema — Spring Boot owned tables
-- Generated from live DB schema
-- ============================================================

-- ── Users ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(255) NOT NULL,
    password            VARCHAR(255) NOT NULL,
    first_name          VARCHAR(255) NOT NULL,
    middle_name         VARCHAR(255),
    last_name           VARCHAR(255) NOT NULL,
    street              VARCHAR(255) NOT NULL,
    barangay            VARCHAR(255) NOT NULL,
    city                VARCHAR(255) NOT NULL,
    province            VARCHAR(255) NOT NULL,
    region              VARCHAR(255) NOT NULL,
    zip_code            INTEGER      NOT NULL,
    role                VARCHAR(255) NOT NULL,
    status              VARCHAR(255) NOT NULL,
    profile_photo_path  VARCHAR(255),
    created_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
    CONSTRAINT users_role_check   CHECK (role   IN ('FARMER','BUYER','ADMIN')),
    CONSTRAINT users_status_check CHECK (status IN ('ACTIVE','SUSPENDED'))
);

-- ── Refresh Tokens ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked    BOOLEAN      NOT NULL,
    user_id    BIGINT       NOT NULL,
    CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token),
    CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ── Password Reset Tokens ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    otp_hash   VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    used       BOOLEAN      NOT NULL,
    user_id    BIGINT       NOT NULL,
    CONSTRAINT fkk3ndxg5xp6v7wd4gjyusp15gq FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ── Carts ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS carts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id   BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uklhsynm4v4ttbdtlbgkmyl9bfy UNIQUE (buyer_id),
    CONSTRAINT fkn2e7ji8t0v41os63pla8kff0r FOREIGN KEY (buyer_id) REFERENCES users(id)
);

-- ── Cart Items ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS cart_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_name       VARCHAR(255)   NOT NULL,
    listing_id      BIGINT         NOT NULL,
    price_per_unit  NUMERIC(10,2)  NOT NULL,
    quantity        INTEGER        NOT NULL,
    unit            VARCHAR(255)   NOT NULL,
    cart_id         BIGINT         NOT NULL,
    CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES carts(id)
);

-- ── Orders ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS orders (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_street    VARCHAR(255)   NOT NULL,
    delivery_barangay  VARCHAR(255)   NOT NULL,
    delivery_city      VARCHAR(255)   NOT NULL,
    delivery_province  VARCHAR(255)   NOT NULL,
    notes              VARCHAR(255),
    status             VARCHAR(255)   NOT NULL,
    total_amount       NUMERIC(12,2)  NOT NULL,
    buyer_id           BIGINT         NOT NULL,
    farmer_id          BIGINT         NOT NULL,
    created_at         TIMESTAMP(6) WITH TIME ZONE,
    updated_at         TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT orders_status_check CHECK (status IN ('PENDING','CONFIRMED','COMPLETED','CANCELLED')),
    CONSTRAINT fkhtx3insd5ge6w486omk4fnk54 FOREIGN KEY (buyer_id)  REFERENCES users(id),
    CONSTRAINT fk44re9virojxhvpsn2jn63bab0 FOREIGN KEY (farmer_id) REFERENCES users(id)
);

-- ── Order Items ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS order_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_name       VARCHAR(255)   NOT NULL,
    listing_id      BIGINT         NOT NULL,
    price_per_unit  NUMERIC(10,2)  NOT NULL,
    quantity        INTEGER        NOT NULL,
    subtotal        NUMERIC(12,2)  NOT NULL,
    unit            VARCHAR(255)   NOT NULL,
    order_id        BIGINT         NOT NULL,
    CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES orders(id)
);

-- ── Order Status Logs ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS order_status_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_status VARCHAR(255) NOT NULL,
    to_status   VARCHAR(255) NOT NULL,
    reason      VARCHAR(255),
    changed_by  BIGINT       NOT NULL,
    order_id    BIGINT       NOT NULL,
    changed_at  TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT order_status_logs_from_status_check CHECK (from_status IN ('PENDING','CONFIRMED','COMPLETED','CANCELLED')),
    CONSTRAINT order_status_logs_to_status_check   CHECK (to_status   IN ('PENDING','CONFIRMED','COMPLETED','CANCELLED')),
    CONSTRAINT fkfs3dssq3pkgrwr97m6kr8xvl FOREIGN KEY (changed_by) REFERENCES users(id),
    CONSTRAINT fkpoehv8fptppd81oysnw7l44by FOREIGN KEY (order_id)   REFERENCES orders(id)
);

-- ── Payments ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS payments (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    method                VARCHAR(255)   NOT NULL,
    status                VARCHAR(255)   NOT NULL,
    amount                NUMERIC(12,2)  NOT NULL,
    reference_number      VARCHAR(255),
    proof_screenshot_path VARCHAR(255),
    admin_notes           VARCHAR(255),
    buyer_id              BIGINT         NOT NULL,
    order_id              BIGINT         NOT NULL,
    reviewed_by           BIGINT,
    reviewed_at           TIMESTAMP(6) WITH TIME ZONE,
    created_at            TIMESTAMP(6) WITH TIME ZONE,
    updated_at            TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk8vo36cen604as7etdfwmyjsxt UNIQUE (order_id),
    CONSTRAINT payments_method_check CHECK (method IN ('CASH_ON_MEETUP','GCASH','PAYMAYA','BANK_TRANSFER')),
    CONSTRAINT payments_status_check CHECK (status IN ('PENDING','SUBMITTED','PAID','FAILED')),
    CONSTRAINT fkg08mb5mpvbebidb9wewidf5al FOREIGN KEY (buyer_id)    REFERENCES users(id),
    CONSTRAINT fk81gagumt0r8y3rmudcgpbk42l FOREIGN KEY (order_id)    REFERENCES orders(id),
    CONSTRAINT fk6jedsr868j0apr7xvtj5xgod6 FOREIGN KEY (reviewed_by) REFERENCES users(id)
);

-- ── Disputes ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS disputes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject          VARCHAR(255) NOT NULL,
    description      TEXT         NOT NULL,
    reference_note   VARCHAR(255),
    attachment_path  VARCHAR(255),
    status           VARCHAR(255) NOT NULL,
    resolution_notes TEXT,
    order_id         BIGINT       NOT NULL,
    raised_by        BIGINT       NOT NULL,
    resolved_by      BIGINT,
    resolved_at      TIMESTAMP(6) WITH TIME ZONE,
    created_at       TIMESTAMP(6) WITH TIME ZONE,
    updated_at       TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT disputes_status_check CHECK (status IN ('OPEN','UNDER_REVIEW','RESOLVED')),
    CONSTRAINT fk7w9qai75udrw8yjppow8vqxa  FOREIGN KEY (order_id)    REFERENCES orders(id),
    CONSTRAINT fkbw5x3hkfwrtdcljq5v9jcine4 FOREIGN KEY (raised_by)   REFERENCES users(id),
    CONSTRAINT fk1mpt52omc4k0co66p6e5i5nq7 FOREIGN KEY (resolved_by) REFERENCES users(id)
);

-- ── Dispute Comments ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS dispute_comments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message         TEXT         NOT NULL,
    attachment_path VARCHAR(255),
    author_id       BIGINT       NOT NULL,
    dispute_id      BIGINT       NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fkpdk99c1c0vne1pa3s48ds2q1h FOREIGN KEY (author_id)  REFERENCES users(id),
    CONSTRAINT fkbcu64j82ebsjh8cvs8ool2cr2 FOREIGN KEY (dispute_id) REFERENCES disputes(id)
);

-- ── Notifications ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS notifications (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type           VARCHAR(255) NOT NULL,
    title          VARCHAR(255) NOT NULL,
    message        TEXT         NOT NULL,
    reference_id   BIGINT,
    reference_type VARCHAR(255),
    read           BOOLEAN      NOT NULL,
    recipient_id   BIGINT       NOT NULL,
    created_at     TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT notifications_type_check CHECK (type IN (
        'ORDER_PLACED','ORDER_CONFIRMED','ORDER_COMPLETED','ORDER_CANCELLED',
        'PAYMENT_SUBMITTED','PAYMENT_CONFIRMED','PAYMENT_FAILED',
        'DISPUTE_OPENED','DISPUTE_UNDER_REVIEW','DISPUTE_RESOLVED','DISPUTE_COMMENT_ADDED',
        'LISTING_APPROVED','LISTING_REJECTED',
        'VERIFICATION_APPROVED','VERIFICATION_REJECTED','VERIFICATION_RESUBMIT_REQUESTED',
        'MESSAGE_RECEIVED'
    )),
    CONSTRAINT fkqqnsjxlwleyjbxlmm213jaj3f FOREIGN KEY (recipient_id) REFERENCES users(id)
);

-- ── Message Threads ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS message_threads (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                VARCHAR(255) NOT NULL,
    reference_id        BIGINT       NOT NULL,
    buyer_unread_count  INTEGER      NOT NULL,
    farmer_unread_count INTEGER      NOT NULL,
    buyer_id            BIGINT       NOT NULL,
    farmer_id           BIGINT       NOT NULL,
    created_at          TIMESTAMP(6) WITH TIME ZONE,
    updated_at          TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk539k8ypw36iyk340sp3t6iepk UNIQUE (buyer_id, farmer_id, reference_id, type),
    CONSTRAINT message_threads_type_check CHECK (type IN ('LISTING','ORDER')),
    CONSTRAINT fk47qfgcdpxdkot28fg4nxtt7wv FOREIGN KEY (buyer_id)  REFERENCES users(id),
    CONSTRAINT fkq15wx96pkdv7d80eqtyltrpvr FOREIGN KEY (farmer_id) REFERENCES users(id)
);

-- ── Messages ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content         TEXT,
    attachment_path VARCHAR(255),
    attachment_name VARCHAR(255),
    read            BOOLEAN NOT NULL,
    sender_id       BIGINT  NOT NULL,
    thread_id       BIGINT  NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fk4ui4nnwntodh6wjvck53dbk9m FOREIGN KEY (sender_id) REFERENCES users(id),
    CONSTRAINT fkp50ts6rmerpigf6yqek16p6ay FOREIGN KEY (thread_id) REFERENCES message_threads(id)
);